spring.application.name=crud_basic
#puerto de la aplicacion
spring.datasource.url=jdbc:mysql://localhost:3306/inventoy
#usuario de la base de datos
spring.datasource.username=root
#password de la base de datos
spring.datasource.password=
#driver de la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#ejecucion de las lineas DDL 
#(create= borra la base de datos si existe y cuando se ejecuta la aplicacion la crea, 
#create-group= cuando se finaliza el producto la borra cuando termine, 
#update = actualiza la base de datos, 
#none= no ejecutara las secuencias ddl, solo se conecta)
spring.jpa.hibernate.ddl-auto=update
#mostrar las consultas
spring.jpa.show-sql=true    
server.port=8080

